import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "katex/dist/katex.min.css"
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight:["400","700","800","900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${nunito} antialiased min-h-screen bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200`}
      >
        {children}
      </body>
    </html>
  );
}
